// GENERATED by scripts/build-flutter-tokens.mjs (lumo-ui) from packages/theme/src/tokens.css — do not edit.
// The same `--lumo-sys-*` semantic tokens as the web theme and the React Native
// package, resolved for Flutter: Colors (oklch → sRGB) for the light and dark
// schemes, logical pixels for radii and control heights (rem × 16 at density 0.9,
// radius scale 1). Brand hue/chroma are the one runtime knob, as everywhere.
import 'dart:math' as math;
import 'dart:ui' show Color;

/// The web theme's ref-tier knobs. Default achromatic, as on the web.
class LumoBrand {
  const LumoBrand({this.hue = 0, this.chroma = 0, this.neutralHue = 0, this.neutralChroma = 0});
  final double hue;
  final double chroma;
  final double neutralHue;
  final double neutralChroma;
  static const achromatic = LumoBrand();
}

/// oklch(L C h) → sRGB Color (gamut-clipped). The ramp's lightness is fixed; a brand turns hue and chroma.
Color oklch(double l, double c, double h) {
  final a = c * math.cos(h * math.pi / 180);
  final b = c * math.sin(h * math.pi / 180);
  final l_ = l + 0.3963377774 * a + 0.2158037573 * b;
  final m_ = l - 0.1055613458 * a - 0.0638541728 * b;
  final s_ = l - 0.0894841775 * a - 1.291485548 * b;
  final l3 = l_ * l_ * l_, m3 = m_ * m_ * m_, s3 = s_ * s_ * s_;
  final lin = [
    4.0767416621 * l3 - 3.3077115913 * m3 + 0.2309699292 * s3,
    -1.2684380046 * l3 + 2.6097574011 * m3 - 0.3413193965 * s3,
    -0.0041960863 * l3 - 0.7034186147 * m3 + 1.707614701 * s3,
  ];
  int channel(double v) {
    final x = v.clamp(0.0, 1.0);
    final srgb = x <= 0.0031308 ? 12.92 * x : 1.055 * math.pow(x, 1 / 2.4) - 0.055;
    return (srgb * 255).round();
  }
  return Color.fromARGB(255, channel(lin[0]), channel(lin[1]), channel(lin[2]));
}

/// The semantic palette of one scheme (`--lumo-sys-*`).
class LumoSchemeColours {
  const LumoSchemeColours({
    required this.bg,
    required this.bgSubtle,
    required this.surface,
    required this.surfaceHover,
    required this.surfaceSunken,
    required this.fg,
    required this.fgMuted,
    required this.fgSubtle,
    required this.fgOnAccent,
    required this.border,
    required this.borderStrong,
    required this.borderControl,
    required this.accent,
    required this.accentHover,
    required this.accentFg,
    required this.positive,
    required this.critical,
    required this.caution,
    required this.focus,
    required this.scrim,
  });
  final Color bg;
  final Color bgSubtle;
  final Color surface;
  final Color surfaceHover;
  final Color surfaceSunken;
  final Color fg;
  final Color fgMuted;
  final Color fgSubtle;
  final Color fgOnAccent;
  final Color border;
  final Color borderStrong;
  final Color borderControl;
  final Color accent;
  final Color accentHover;
  final Color accentFg;
  final Color positive;
  final Color critical;
  final Color caution;
  final Color focus;
  final Color scrim;
}

LumoSchemeColours lightColours([LumoBrand brand = LumoBrand.achromatic]) => LumoSchemeColours(
      bg: oklch(0.985, brand.neutralChroma, brand.neutralHue),
      bgSubtle: oklch(0.97, brand.neutralChroma, brand.neutralHue),
      surface: Color(0xFFFFFFFF),
      surfaceHover: oklch(0.97, brand.neutralChroma, brand.neutralHue),
      surfaceSunken: oklch(0.97, brand.neutralChroma, brand.neutralHue),
      fg: oklch(0.145, brand.neutralChroma, brand.neutralHue),
      fgMuted: oklch(0.5, brand.neutralChroma, brand.neutralHue),
      fgSubtle: oklch(0.54, brand.neutralChroma, brand.neutralHue),
      fgOnAccent: oklch(0.985, brand.neutralChroma, brand.neutralHue),
      border: oklch(0.922, brand.neutralChroma, brand.neutralHue),
      borderStrong: oklch(0.845, brand.neutralChroma, brand.neutralHue),
      borderControl: oklch(0.64, brand.neutralChroma, brand.neutralHue),
      accent: oklch(0.205, brand.chroma, brand.hue),
      accentHover: oklch(0.32, brand.chroma, brand.hue),
      accentFg: oklch(0.985, brand.neutralChroma, brand.neutralHue),
      positive: Color(0xFF00763F),
      critical: Color(0xFFBF0000),
      caution: Color(0xFF8F5B00),
      focus: oklch(0.32, brand.chroma, brand.hue),
      scrim: Color(0x80000000),
    );

LumoSchemeColours darkColours([LumoBrand brand = LumoBrand.achromatic]) => LumoSchemeColours(
      bg: oklch(0.145, brand.neutralChroma, brand.neutralHue),
      bgSubtle: oklch(0.205, brand.neutralChroma, brand.neutralHue),
      surface: oklch(0.205, brand.neutralChroma, brand.neutralHue),
      surfaceHover: oklch(0.269, brand.neutralChroma, brand.neutralHue),
      surfaceSunken: oklch(0.145, brand.neutralChroma, brand.neutralHue),
      fg: oklch(0.985, brand.neutralChroma, brand.neutralHue),
      fgMuted: oklch(0.71, brand.neutralChroma, brand.neutralHue),
      fgSubtle: oklch(0.66, brand.neutralChroma, brand.neutralHue),
      fgOnAccent: oklch(0.205, brand.neutralChroma, brand.neutralHue),
      border: oklch(0.383, brand.neutralChroma, brand.neutralHue),
      borderStrong: oklch(0.47, brand.neutralChroma, brand.neutralHue),
      borderControl: oklch(0.556, brand.neutralChroma, brand.neutralHue),
      accent: oklch(0.922, brand.chroma, brand.hue),
      accentHover: oklch(0.75, brand.chroma, brand.hue),
      accentFg: oklch(0.205, brand.neutralChroma, brand.neutralHue),
      positive: Color(0xFF3BB974),
      critical: Color(0xFFFF6467),
      caution: Color(0xFFEBA941),
      focus: oklch(0.922, brand.chroma, brand.hue),
      scrim: Color(0xB8000000),
    );

/// Radii in logical pixels (web: --lumo-sys-radius-*).
class LumoRadius {
  static const double sm = 6;
  static const double md = 8;
  static const double lg = 10;
}
/// Control heights at the default density (web: --lumo-ref-control-*).
class LumoControl {
  static const double sm = 29;
  static const double md = 36;
  static const double lg = 44;
}
/// Focus ring (web: --lumo-sys-focus-width / -offset).
class LumoFocus {
  static const double width = 2;
  static const double offset = 2;
}
