// GENERATED by scripts/build-mobile-styles.mjs (lumo-ui) from packages/mobile/lib/src/styles.dart — do not edit.
//
// The mechanical half of the per-widget customisation surface: `copyWith`,
// `merge`, `lerp`, `==` and `hashCode` for every family style, and the same for
// `LumoStyles`. Written once here so that adding a family costs a style class
// and one registry line, not five more methods nobody re-reads. The generator is
// also where the APPEARANCE-ONLY rule lives: it can emit `lerp` only for types
// that carry no meaning, so a field that could reach a name, a role or the
// direction fails the BUILD rather than the review.
part of 'styles.dart';

mixin _$LumoCardStyle {
  EdgeInsetsGeometry? get padding;
  BorderRadiusGeometry? get borderRadius;
  Map<LumoCardVariant, Color>? get background;
  Color? get pressedBackground;
  Color? get borderColour;
  double? get borderWidth;
  List<BoxShadow>? get shadow;
  Duration? get pressDuration;
  double? get disabledOpacity;
  TextStyle? get titleTextStyle;
  TextStyle? get descriptionTextStyle;
  double? get headerGap;
  double? get headerDescriptionGap;
  double? get headerActionGap;
  double? get footerGap;
  double? get footerActionGap;
  Color? get footerRuleColour;

  /// This style with the given fields replaced. A null argument KEEPS the
  /// current value — `copyWith` cannot clear a field; construct a fresh style
  /// for that.
  LumoCardStyle copyWith({
    EdgeInsetsGeometry? padding,
    BorderRadiusGeometry? borderRadius,
    Map<LumoCardVariant, Color>? background,
    Color? pressedBackground,
    Color? borderColour,
    double? borderWidth,
    List<BoxShadow>? shadow,
    Duration? pressDuration,
    double? disabledOpacity,
    TextStyle? titleTextStyle,
    TextStyle? descriptionTextStyle,
    double? headerGap,
    double? headerDescriptionGap,
    double? headerActionGap,
    double? footerGap,
    double? footerActionGap,
    Color? footerRuleColour,
  }) =>
      LumoCardStyle(
        padding: padding ?? this.padding,
        borderRadius: borderRadius ?? this.borderRadius,
        background: background ?? this.background,
        pressedBackground: pressedBackground ?? this.pressedBackground,
        borderColour: borderColour ?? this.borderColour,
        borderWidth: borderWidth ?? this.borderWidth,
        shadow: shadow ?? this.shadow,
        pressDuration: pressDuration ?? this.pressDuration,
        disabledOpacity: disabledOpacity ?? this.disabledOpacity,
        titleTextStyle: titleTextStyle ?? this.titleTextStyle,
        descriptionTextStyle: descriptionTextStyle ?? this.descriptionTextStyle,
        headerGap: headerGap ?? this.headerGap,
        headerDescriptionGap: headerDescriptionGap ?? this.headerDescriptionGap,
        headerActionGap: headerActionGap ?? this.headerActionGap,
        footerGap: footerGap ?? this.footerGap,
        footerActionGap: footerActionGap ?? this.footerActionGap,
        footerRuleColour: footerRuleColour ?? this.footerRuleColour,
      );

  /// `other`'s set fields win; the rest stay this object's. A per-step or
  /// per-variant table merges KEY BY KEY, so a theme that moves one step and a
  /// call site that moves another both take effect; every other field replaces.
  LumoCardStyle merge(LumoCardStyle? other) => other == null
      ? copyWith()
      : LumoCardStyle(
          padding: other.padding ?? padding,
          borderRadius: other.borderRadius ?? borderRadius,
          background: (background == null && other.background == null) ? null : <LumoCardVariant, Color>{...?background, ...?other.background},
          pressedBackground: other.pressedBackground ?? pressedBackground,
          borderColour: other.borderColour ?? borderColour,
          borderWidth: other.borderWidth ?? borderWidth,
          shadow: other.shadow ?? shadow,
          pressDuration: other.pressDuration ?? pressDuration,
          disabledOpacity: other.disabledOpacity ?? disabledOpacity,
          titleTextStyle: other.titleTextStyle ?? titleTextStyle,
          descriptionTextStyle: other.descriptionTextStyle ?? descriptionTextStyle,
          headerGap: other.headerGap ?? headerGap,
          headerDescriptionGap: other.headerDescriptionGap ?? headerDescriptionGap,
          headerActionGap: other.headerActionGap ?? headerActionGap,
          footerGap: other.footerGap ?? footerGap,
          footerActionGap: other.footerActionGap ?? footerActionGap,
          footerRuleColour: other.footerRuleColour ?? footerRuleColour,
        );

  /// Interpolate towards `other` — what `ThemeData.lerp` calls when a theme
  /// animates between two schemes. A field with no half-way value snaps at
  /// t = 0.5 rather than inventing one.
  LumoCardStyle lerp(LumoCardStyle other, double t) => LumoCardStyle(
        padding: EdgeInsetsGeometry.lerp(padding, other.padding, t),
        borderRadius: BorderRadiusGeometry.lerp(borderRadius, other.borderRadius, t),
        background: _lerpMap<LumoCardVariant, Color>(background, other.background, t, Color.lerp),
        pressedBackground: Color.lerp(pressedBackground, other.pressedBackground, t),
        borderColour: Color.lerp(borderColour, other.borderColour, t),
        borderWidth: lerpDouble(borderWidth, other.borderWidth, t),
        shadow: BoxShadow.lerpList(shadow, other.shadow, t),
        pressDuration: (t < 0.5 ? pressDuration : other.pressDuration),
        disabledOpacity: lerpDouble(disabledOpacity, other.disabledOpacity, t),
        titleTextStyle: TextStyle.lerp(titleTextStyle, other.titleTextStyle, t),
        descriptionTextStyle: TextStyle.lerp(descriptionTextStyle, other.descriptionTextStyle, t),
        headerGap: lerpDouble(headerGap, other.headerGap, t),
        headerDescriptionGap: lerpDouble(headerDescriptionGap, other.headerDescriptionGap, t),
        headerActionGap: lerpDouble(headerActionGap, other.headerActionGap, t),
        footerGap: lerpDouble(footerGap, other.footerGap, t),
        footerActionGap: lerpDouble(footerActionGap, other.footerActionGap, t),
        footerRuleColour: Color.lerp(footerRuleColour, other.footerRuleColour, t),
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LumoCardStyle &&
          padding == other.padding &&
          borderRadius == other.borderRadius &&
          mapEquals(background, other.background) &&
          pressedBackground == other.pressedBackground &&
          borderColour == other.borderColour &&
          borderWidth == other.borderWidth &&
          listEquals(shadow, other.shadow) &&
          pressDuration == other.pressDuration &&
          disabledOpacity == other.disabledOpacity &&
          titleTextStyle == other.titleTextStyle &&
          descriptionTextStyle == other.descriptionTextStyle &&
          headerGap == other.headerGap &&
          headerDescriptionGap == other.headerDescriptionGap &&
          headerActionGap == other.headerActionGap &&
          footerGap == other.footerGap &&
          footerActionGap == other.footerActionGap &&
          footerRuleColour == other.footerRuleColour;

  @override
  int get hashCode => Object.hashAll([
        padding,
        borderRadius,
        _hashMap(background),
        pressedBackground,
        borderColour,
        borderWidth,
        shadow == null ? null : Object.hashAll(shadow!),
        pressDuration,
        disabledOpacity,
        titleTextStyle,
        descriptionTextStyle,
        headerGap,
        headerDescriptionGap,
        headerActionGap,
        footerGap,
        footerActionGap,
        footerRuleColour,
      ]);
}

mixin _$LumoButtonStyle {
  Map<LumoButtonSize, double>? get height;
  Map<LumoButtonSize, double>? get inlinePadding;
  Map<LumoButtonSize, double>? get fontSize;
  FontWeight? get fontWeight;
  BorderRadiusGeometry? get borderRadius;
  Map<LumoButtonVariant, Color>? get background;
  Map<LumoButtonVariant, Color>? get pressedBackground;
  Map<LumoButtonVariant, Color>? get foreground;
  Map<LumoButtonVariant, Color>? get borderColour;
  double? get borderWidth;
  double? get disabledOpacity;
  double? get minTapTarget;

  /// This style with the given fields replaced. A null argument KEEPS the
  /// current value — `copyWith` cannot clear a field; construct a fresh style
  /// for that.
  LumoButtonStyle copyWith({
    Map<LumoButtonSize, double>? height,
    Map<LumoButtonSize, double>? inlinePadding,
    Map<LumoButtonSize, double>? fontSize,
    FontWeight? fontWeight,
    BorderRadiusGeometry? borderRadius,
    Map<LumoButtonVariant, Color>? background,
    Map<LumoButtonVariant, Color>? pressedBackground,
    Map<LumoButtonVariant, Color>? foreground,
    Map<LumoButtonVariant, Color>? borderColour,
    double? borderWidth,
    double? disabledOpacity,
    double? minTapTarget,
  }) =>
      LumoButtonStyle(
        height: height ?? this.height,
        inlinePadding: inlinePadding ?? this.inlinePadding,
        fontSize: fontSize ?? this.fontSize,
        fontWeight: fontWeight ?? this.fontWeight,
        borderRadius: borderRadius ?? this.borderRadius,
        background: background ?? this.background,
        pressedBackground: pressedBackground ?? this.pressedBackground,
        foreground: foreground ?? this.foreground,
        borderColour: borderColour ?? this.borderColour,
        borderWidth: borderWidth ?? this.borderWidth,
        disabledOpacity: disabledOpacity ?? this.disabledOpacity,
        minTapTarget: minTapTarget ?? this.minTapTarget,
      );

  /// `other`'s set fields win; the rest stay this object's. A per-step or
  /// per-variant table merges KEY BY KEY, so a theme that moves one step and a
  /// call site that moves another both take effect; every other field replaces.
  LumoButtonStyle merge(LumoButtonStyle? other) => other == null
      ? copyWith()
      : LumoButtonStyle(
          height: (height == null && other.height == null) ? null : <LumoButtonSize, double>{...?height, ...?other.height},
          inlinePadding: (inlinePadding == null && other.inlinePadding == null) ? null : <LumoButtonSize, double>{...?inlinePadding, ...?other.inlinePadding},
          fontSize: (fontSize == null && other.fontSize == null) ? null : <LumoButtonSize, double>{...?fontSize, ...?other.fontSize},
          fontWeight: other.fontWeight ?? fontWeight,
          borderRadius: other.borderRadius ?? borderRadius,
          background: (background == null && other.background == null) ? null : <LumoButtonVariant, Color>{...?background, ...?other.background},
          pressedBackground: (pressedBackground == null && other.pressedBackground == null) ? null : <LumoButtonVariant, Color>{...?pressedBackground, ...?other.pressedBackground},
          foreground: (foreground == null && other.foreground == null) ? null : <LumoButtonVariant, Color>{...?foreground, ...?other.foreground},
          borderColour: (borderColour == null && other.borderColour == null) ? null : <LumoButtonVariant, Color>{...?borderColour, ...?other.borderColour},
          borderWidth: other.borderWidth ?? borderWidth,
          disabledOpacity: other.disabledOpacity ?? disabledOpacity,
          minTapTarget: other.minTapTarget ?? minTapTarget,
        );

  /// Interpolate towards `other` — what `ThemeData.lerp` calls when a theme
  /// animates between two schemes. A field with no half-way value snaps at
  /// t = 0.5 rather than inventing one.
  LumoButtonStyle lerp(LumoButtonStyle other, double t) => LumoButtonStyle(
        height: _lerpMap<LumoButtonSize, double>(height, other.height, t, lerpDouble),
        inlinePadding: _lerpMap<LumoButtonSize, double>(inlinePadding, other.inlinePadding, t, lerpDouble),
        fontSize: _lerpMap<LumoButtonSize, double>(fontSize, other.fontSize, t, lerpDouble),
        fontWeight: FontWeight.lerp(fontWeight, other.fontWeight, t),
        borderRadius: BorderRadiusGeometry.lerp(borderRadius, other.borderRadius, t),
        background: _lerpMap<LumoButtonVariant, Color>(background, other.background, t, Color.lerp),
        pressedBackground: _lerpMap<LumoButtonVariant, Color>(pressedBackground, other.pressedBackground, t, Color.lerp),
        foreground: _lerpMap<LumoButtonVariant, Color>(foreground, other.foreground, t, Color.lerp),
        borderColour: _lerpMap<LumoButtonVariant, Color>(borderColour, other.borderColour, t, Color.lerp),
        borderWidth: lerpDouble(borderWidth, other.borderWidth, t),
        disabledOpacity: lerpDouble(disabledOpacity, other.disabledOpacity, t),
        minTapTarget: lerpDouble(minTapTarget, other.minTapTarget, t),
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LumoButtonStyle &&
          mapEquals(height, other.height) &&
          mapEquals(inlinePadding, other.inlinePadding) &&
          mapEquals(fontSize, other.fontSize) &&
          fontWeight == other.fontWeight &&
          borderRadius == other.borderRadius &&
          mapEquals(background, other.background) &&
          mapEquals(pressedBackground, other.pressedBackground) &&
          mapEquals(foreground, other.foreground) &&
          mapEquals(borderColour, other.borderColour) &&
          borderWidth == other.borderWidth &&
          disabledOpacity == other.disabledOpacity &&
          minTapTarget == other.minTapTarget;

  @override
  int get hashCode => Object.hashAll([
        _hashMap(height),
        _hashMap(inlinePadding),
        _hashMap(fontSize),
        fontWeight,
        borderRadius,
        _hashMap(background),
        _hashMap(pressedBackground),
        _hashMap(foreground),
        _hashMap(borderColour),
        borderWidth,
        disabledOpacity,
        minTapTarget,
      ]);
}

mixin _$LumoStyles on ThemeExtension<LumoStyles> {
  LumoButtonStyle get button;
  LumoCardStyle get card;

  @override
  LumoStyles copyWith({LumoButtonStyle? button, LumoCardStyle? card}) => LumoStyles(button: button ?? this.button, card: card ?? this.card);

  @override
  LumoStyles lerp(covariant LumoStyles? other, double t) => other == null ? copyWith() : LumoStyles(button: button.lerp(other.button, t), card: card.lerp(other.card, t));

  @override
  bool operator ==(Object other) => identical(this, other) || other is LumoStyles && other.button == button && other.card == card;

  @override
  int get hashCode => Object.hashAll([button, card]);
}

/// Two per-step tables interpolated key by key. A key only ONE side carries has
/// nothing to interpolate against, so it SNAPS at the half-way point: fading a
/// value towards a default the other side never named draws a colour that is in
/// neither theme.
Map<K, V>? _lerpMap<K, V>(Map<K, V>? a, Map<K, V>? b, double t, V? Function(V?, V?, double) lerp) {
  if (a == null && b == null) return null;
  final out = <K, V>{};
  for (final key in <K>{...?a?.keys, ...?b?.keys}) {
    final x = a?[key];
    final y = b?[key];
    final v = x == null || y == null ? (t < 0.5 ? x : y) : lerp(x, y, t);
    if (v != null) out[key] = v;
  }
  return out;
}


/// Order-independent, because a table's order is not part of its meaning.
int? _hashMap<K, V>(Map<K, V>? map) => map == null ? null : Object.hashAllUnordered(map.entries.map((e) => Object.hash(e.key, e.value)));
