// GENERATED by scripts/build-mobile-styles.mjs (lumo-ui) from packages/mobile/lib/src/styles.dart — do not edit.
//
// The mechanical half of the per-widget customisation surface: `copyWith`,
// `merge`, `lerp`, `==` and `hashCode` for every family style, and the same for
// `LumoStyles`. Written once here so that adding a family costs a style class
// and one registry line, not five more methods nobody re-reads. The generator is
// also where the APPEARANCE-ONLY rule lives: it can emit `lerp` only for types
// that carry no meaning, so a field that could reach a name, a role or the
// direction fails the BUILD rather than the review.
part of 'styles.dart';

mixin _$LumoButtonStyle {
  Map<LumoButtonSize, double>? get height;
  Map<LumoButtonSize, double>? get inlinePadding;
  Map<LumoButtonSize, double>? get fontSize;
  FontWeight? get fontWeight;
  BorderRadiusGeometry? get borderRadius;
  Map<LumoButtonVariant, Color>? get background;
  Map<LumoButtonVariant, Color>? get pressedBackground;
  Map<LumoButtonVariant, Color>? get foreground;
  Map<LumoButtonVariant, Color>? get borderColour;
  double? get borderWidth;
  double? get disabledOpacity;
  double? get minTapTarget;

  /// This style with the given fields replaced. A null argument KEEPS the
  /// current value — `copyWith` cannot clear a field; construct a fresh style
  /// for that.
  LumoButtonStyle copyWith({
    Map<LumoButtonSize, double>? height,
    Map<LumoButtonSize, double>? inlinePadding,
    Map<LumoButtonSize, double>? fontSize,
    FontWeight? fontWeight,
    BorderRadiusGeometry? borderRadius,
    Map<LumoButtonVariant, Color>? background,
    Map<LumoButtonVariant, Color>? pressedBackground,
    Map<LumoButtonVariant, Color>? foreground,
    Map<LumoButtonVariant, Color>? borderColour,
    double? borderWidth,
    double? disabledOpacity,
    double? minTapTarget,
  }) =>
      LumoButtonStyle(
        height: height ?? this.height,
        inlinePadding: inlinePadding ?? this.inlinePadding,
        fontSize: fontSize ?? this.fontSize,
        fontWeight: fontWeight ?? this.fontWeight,
        borderRadius: borderRadius ?? this.borderRadius,
        background: background ?? this.background,
        pressedBackground: pressedBackground ?? this.pressedBackground,
        foreground: foreground ?? this.foreground,
        borderColour: borderColour ?? this.borderColour,
        borderWidth: borderWidth ?? this.borderWidth,
        disabledOpacity: disabledOpacity ?? this.disabledOpacity,
        minTapTarget: minTapTarget ?? this.minTapTarget,
      );

  /// `other`'s set fields win; the rest stay this object's. A per-step or
  /// per-variant table merges KEY BY KEY, so a theme that moves one step and a
  /// call site that moves another both take effect; every other field replaces.
  LumoButtonStyle merge(LumoButtonStyle? other) => other == null
      ? copyWith()
      : LumoButtonStyle(
          height: (height == null && other.height == null) ? null : <LumoButtonSize, double>{...?height, ...?other.height},
          inlinePadding: (inlinePadding == null && other.inlinePadding == null) ? null : <LumoButtonSize, double>{...?inlinePadding, ...?other.inlinePadding},
          fontSize: (fontSize == null && other.fontSize == null) ? null : <LumoButtonSize, double>{...?fontSize, ...?other.fontSize},
          fontWeight: other.fontWeight ?? fontWeight,
          borderRadius: other.borderRadius ?? borderRadius,
          background: (background == null && other.background == null) ? null : <LumoButtonVariant, Color>{...?background, ...?other.background},
          pressedBackground: (pressedBackground == null && other.pressedBackground == null) ? null : <LumoButtonVariant, Color>{...?pressedBackground, ...?other.pressedBackground},
          foreground: (foreground == null && other.foreground == null) ? null : <LumoButtonVariant, Color>{...?foreground, ...?other.foreground},
          borderColour: (borderColour == null && other.borderColour == null) ? null : <LumoButtonVariant, Color>{...?borderColour, ...?other.borderColour},
          borderWidth: other.borderWidth ?? borderWidth,
          disabledOpacity: other.disabledOpacity ?? disabledOpacity,
          minTapTarget: other.minTapTarget ?? minTapTarget,
        );

  /// Interpolate towards `other` — what `ThemeData.lerp` calls when a theme
  /// animates between two schemes. A field with no half-way value snaps at
  /// t = 0.5 rather than inventing one.
  LumoButtonStyle lerp(LumoButtonStyle other, double t) => LumoButtonStyle(
        height: _lerpMap<LumoButtonSize, double>(height, other.height, t, lerpDouble),
        inlinePadding: _lerpMap<LumoButtonSize, double>(inlinePadding, other.inlinePadding, t, lerpDouble),
        fontSize: _lerpMap<LumoButtonSize, double>(fontSize, other.fontSize, t, lerpDouble),
        fontWeight: FontWeight.lerp(fontWeight, other.fontWeight, t),
        borderRadius: BorderRadiusGeometry.lerp(borderRadius, other.borderRadius, t),
        background: _lerpMap<LumoButtonVariant, Color>(background, other.background, t, Color.lerp),
        pressedBackground: _lerpMap<LumoButtonVariant, Color>(pressedBackground, other.pressedBackground, t, Color.lerp),
        foreground: _lerpMap<LumoButtonVariant, Color>(foreground, other.foreground, t, Color.lerp),
        borderColour: _lerpMap<LumoButtonVariant, Color>(borderColour, other.borderColour, t, Color.lerp),
        borderWidth: lerpDouble(borderWidth, other.borderWidth, t),
        disabledOpacity: lerpDouble(disabledOpacity, other.disabledOpacity, t),
        minTapTarget: lerpDouble(minTapTarget, other.minTapTarget, t),
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LumoButtonStyle &&
          mapEquals(height, other.height) &&
          mapEquals(inlinePadding, other.inlinePadding) &&
          mapEquals(fontSize, other.fontSize) &&
          fontWeight == other.fontWeight &&
          borderRadius == other.borderRadius &&
          mapEquals(background, other.background) &&
          mapEquals(pressedBackground, other.pressedBackground) &&
          mapEquals(foreground, other.foreground) &&
          mapEquals(borderColour, other.borderColour) &&
          borderWidth == other.borderWidth &&
          disabledOpacity == other.disabledOpacity &&
          minTapTarget == other.minTapTarget;

  @override
  int get hashCode => Object.hashAll([
        _hashMap(height),
        _hashMap(inlinePadding),
        _hashMap(fontSize),
        fontWeight,
        borderRadius,
        _hashMap(background),
        _hashMap(pressedBackground),
        _hashMap(foreground),
        _hashMap(borderColour),
        borderWidth,
        disabledOpacity,
        minTapTarget,
      ]);
}

mixin _$LumoCardStyle {
  EdgeInsetsGeometry? get padding;
  BorderRadiusGeometry? get borderRadius;
  Map<LumoCardVariant, Color>? get background;
  Color? get pressedBackground;
  Color? get borderColour;
  double? get borderWidth;
  List<BoxShadow>? get shadow;
  Duration? get pressDuration;
  double? get disabledOpacity;
  TextStyle? get titleTextStyle;
  TextStyle? get descriptionTextStyle;
  double? get headerGap;
  double? get headerDescriptionGap;
  double? get headerActionGap;
  double? get footerGap;
  double? get footerActionGap;
  Color? get footerRuleColour;

  /// This style with the given fields replaced. A null argument KEEPS the
  /// current value — `copyWith` cannot clear a field; construct a fresh style
  /// for that.
  LumoCardStyle copyWith({
    EdgeInsetsGeometry? padding,
    BorderRadiusGeometry? borderRadius,
    Map<LumoCardVariant, Color>? background,
    Color? pressedBackground,
    Color? borderColour,
    double? borderWidth,
    List<BoxShadow>? shadow,
    Duration? pressDuration,
    double? disabledOpacity,
    TextStyle? titleTextStyle,
    TextStyle? descriptionTextStyle,
    double? headerGap,
    double? headerDescriptionGap,
    double? headerActionGap,
    double? footerGap,
    double? footerActionGap,
    Color? footerRuleColour,
  }) =>
      LumoCardStyle(
        padding: padding ?? this.padding,
        borderRadius: borderRadius ?? this.borderRadius,
        background: background ?? this.background,
        pressedBackground: pressedBackground ?? this.pressedBackground,
        borderColour: borderColour ?? this.borderColour,
        borderWidth: borderWidth ?? this.borderWidth,
        shadow: shadow ?? this.shadow,
        pressDuration: pressDuration ?? this.pressDuration,
        disabledOpacity: disabledOpacity ?? this.disabledOpacity,
        titleTextStyle: titleTextStyle ?? this.titleTextStyle,
        descriptionTextStyle: descriptionTextStyle ?? this.descriptionTextStyle,
        headerGap: headerGap ?? this.headerGap,
        headerDescriptionGap: headerDescriptionGap ?? this.headerDescriptionGap,
        headerActionGap: headerActionGap ?? this.headerActionGap,
        footerGap: footerGap ?? this.footerGap,
        footerActionGap: footerActionGap ?? this.footerActionGap,
        footerRuleColour: footerRuleColour ?? this.footerRuleColour,
      );

  /// `other`'s set fields win; the rest stay this object's. A per-step or
  /// per-variant table merges KEY BY KEY, so a theme that moves one step and a
  /// call site that moves another both take effect; every other field replaces.
  LumoCardStyle merge(LumoCardStyle? other) => other == null
      ? copyWith()
      : LumoCardStyle(
          padding: other.padding ?? padding,
          borderRadius: other.borderRadius ?? borderRadius,
          background: (background == null && other.background == null) ? null : <LumoCardVariant, Color>{...?background, ...?other.background},
          pressedBackground: other.pressedBackground ?? pressedBackground,
          borderColour: other.borderColour ?? borderColour,
          borderWidth: other.borderWidth ?? borderWidth,
          shadow: other.shadow ?? shadow,
          pressDuration: other.pressDuration ?? pressDuration,
          disabledOpacity: other.disabledOpacity ?? disabledOpacity,
          titleTextStyle: other.titleTextStyle ?? titleTextStyle,
          descriptionTextStyle: other.descriptionTextStyle ?? descriptionTextStyle,
          headerGap: other.headerGap ?? headerGap,
          headerDescriptionGap: other.headerDescriptionGap ?? headerDescriptionGap,
          headerActionGap: other.headerActionGap ?? headerActionGap,
          footerGap: other.footerGap ?? footerGap,
          footerActionGap: other.footerActionGap ?? footerActionGap,
          footerRuleColour: other.footerRuleColour ?? footerRuleColour,
        );

  /// Interpolate towards `other` — what `ThemeData.lerp` calls when a theme
  /// animates between two schemes. A field with no half-way value snaps at
  /// t = 0.5 rather than inventing one.
  LumoCardStyle lerp(LumoCardStyle other, double t) => LumoCardStyle(
        padding: EdgeInsetsGeometry.lerp(padding, other.padding, t),
        borderRadius: BorderRadiusGeometry.lerp(borderRadius, other.borderRadius, t),
        background: _lerpMap<LumoCardVariant, Color>(background, other.background, t, Color.lerp),
        pressedBackground: Color.lerp(pressedBackground, other.pressedBackground, t),
        borderColour: Color.lerp(borderColour, other.borderColour, t),
        borderWidth: lerpDouble(borderWidth, other.borderWidth, t),
        shadow: BoxShadow.lerpList(shadow, other.shadow, t),
        pressDuration: (t < 0.5 ? pressDuration : other.pressDuration),
        disabledOpacity: lerpDouble(disabledOpacity, other.disabledOpacity, t),
        titleTextStyle: TextStyle.lerp(titleTextStyle, other.titleTextStyle, t),
        descriptionTextStyle: TextStyle.lerp(descriptionTextStyle, other.descriptionTextStyle, t),
        headerGap: lerpDouble(headerGap, other.headerGap, t),
        headerDescriptionGap: lerpDouble(headerDescriptionGap, other.headerDescriptionGap, t),
        headerActionGap: lerpDouble(headerActionGap, other.headerActionGap, t),
        footerGap: lerpDouble(footerGap, other.footerGap, t),
        footerActionGap: lerpDouble(footerActionGap, other.footerActionGap, t),
        footerRuleColour: Color.lerp(footerRuleColour, other.footerRuleColour, t),
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LumoCardStyle &&
          padding == other.padding &&
          borderRadius == other.borderRadius &&
          mapEquals(background, other.background) &&
          pressedBackground == other.pressedBackground &&
          borderColour == other.borderColour &&
          borderWidth == other.borderWidth &&
          listEquals(shadow, other.shadow) &&
          pressDuration == other.pressDuration &&
          disabledOpacity == other.disabledOpacity &&
          titleTextStyle == other.titleTextStyle &&
          descriptionTextStyle == other.descriptionTextStyle &&
          headerGap == other.headerGap &&
          headerDescriptionGap == other.headerDescriptionGap &&
          headerActionGap == other.headerActionGap &&
          footerGap == other.footerGap &&
          footerActionGap == other.footerActionGap &&
          footerRuleColour == other.footerRuleColour;

  @override
  int get hashCode => Object.hashAll([
        padding,
        borderRadius,
        _hashMap(background),
        pressedBackground,
        borderColour,
        borderWidth,
        shadow == null ? null : Object.hashAll(shadow!),
        pressDuration,
        disabledOpacity,
        titleTextStyle,
        descriptionTextStyle,
        headerGap,
        headerDescriptionGap,
        headerActionGap,
        footerGap,
        footerActionGap,
        footerRuleColour,
      ]);
}

mixin _$LumoItemStyle {
  Map<LumoItemSize, double>? get gap;
  Map<LumoItemSize, double>? get inlinePadding;
  Map<LumoItemSize, double>? get blockPadding;
  double? get minHeight;
  BorderRadiusGeometry? get borderRadius;
  Map<LumoItemVariant, Color>? get background;
  Color? get selectedBackground;
  Color? get pressedBackground;
  Color? get borderColour;
  double? get borderWidth;
  TextStyle? get titleTextStyle;
  TextStyle? get descriptionTextStyle;
  double? get textGap;
  IconThemeData? get iconTheme;
  Color? get chevronColour;
  double? get chevronSize;
  Color? get dividerColour;
  double? get dividerThickness;
  double? get disabledOpacity;
  TextStyle? get groupLabelTextStyle;
  double? get groupLabelGap;
  double? get groupGap;
  EdgeInsetsGeometry? get listPadding;
  double? get listGap;
  TextStyle? get emptyTextStyle;
  Color? get selectedIconColour;

  /// This style with the given fields replaced. A null argument KEEPS the
  /// current value — `copyWith` cannot clear a field; construct a fresh style
  /// for that.
  LumoItemStyle copyWith({
    Map<LumoItemSize, double>? gap,
    Map<LumoItemSize, double>? inlinePadding,
    Map<LumoItemSize, double>? blockPadding,
    double? minHeight,
    BorderRadiusGeometry? borderRadius,
    Map<LumoItemVariant, Color>? background,
    Color? selectedBackground,
    Color? pressedBackground,
    Color? borderColour,
    double? borderWidth,
    TextStyle? titleTextStyle,
    TextStyle? descriptionTextStyle,
    double? textGap,
    IconThemeData? iconTheme,
    Color? chevronColour,
    double? chevronSize,
    Color? dividerColour,
    double? dividerThickness,
    double? disabledOpacity,
    TextStyle? groupLabelTextStyle,
    double? groupLabelGap,
    double? groupGap,
    EdgeInsetsGeometry? listPadding,
    double? listGap,
    TextStyle? emptyTextStyle,
    Color? selectedIconColour,
  }) =>
      LumoItemStyle(
        gap: gap ?? this.gap,
        inlinePadding: inlinePadding ?? this.inlinePadding,
        blockPadding: blockPadding ?? this.blockPadding,
        minHeight: minHeight ?? this.minHeight,
        borderRadius: borderRadius ?? this.borderRadius,
        background: background ?? this.background,
        selectedBackground: selectedBackground ?? this.selectedBackground,
        pressedBackground: pressedBackground ?? this.pressedBackground,
        borderColour: borderColour ?? this.borderColour,
        borderWidth: borderWidth ?? this.borderWidth,
        titleTextStyle: titleTextStyle ?? this.titleTextStyle,
        descriptionTextStyle: descriptionTextStyle ?? this.descriptionTextStyle,
        textGap: textGap ?? this.textGap,
        iconTheme: iconTheme ?? this.iconTheme,
        chevronColour: chevronColour ?? this.chevronColour,
        chevronSize: chevronSize ?? this.chevronSize,
        dividerColour: dividerColour ?? this.dividerColour,
        dividerThickness: dividerThickness ?? this.dividerThickness,
        disabledOpacity: disabledOpacity ?? this.disabledOpacity,
        groupLabelTextStyle: groupLabelTextStyle ?? this.groupLabelTextStyle,
        groupLabelGap: groupLabelGap ?? this.groupLabelGap,
        groupGap: groupGap ?? this.groupGap,
        listPadding: listPadding ?? this.listPadding,
        listGap: listGap ?? this.listGap,
        emptyTextStyle: emptyTextStyle ?? this.emptyTextStyle,
        selectedIconColour: selectedIconColour ?? this.selectedIconColour,
      );

  /// `other`'s set fields win; the rest stay this object's. A per-step or
  /// per-variant table merges KEY BY KEY, so a theme that moves one step and a
  /// call site that moves another both take effect; every other field replaces.
  LumoItemStyle merge(LumoItemStyle? other) => other == null
      ? copyWith()
      : LumoItemStyle(
          gap: (gap == null && other.gap == null) ? null : <LumoItemSize, double>{...?gap, ...?other.gap},
          inlinePadding: (inlinePadding == null && other.inlinePadding == null) ? null : <LumoItemSize, double>{...?inlinePadding, ...?other.inlinePadding},
          blockPadding: (blockPadding == null && other.blockPadding == null) ? null : <LumoItemSize, double>{...?blockPadding, ...?other.blockPadding},
          minHeight: other.minHeight ?? minHeight,
          borderRadius: other.borderRadius ?? borderRadius,
          background: (background == null && other.background == null) ? null : <LumoItemVariant, Color>{...?background, ...?other.background},
          selectedBackground: other.selectedBackground ?? selectedBackground,
          pressedBackground: other.pressedBackground ?? pressedBackground,
          borderColour: other.borderColour ?? borderColour,
          borderWidth: other.borderWidth ?? borderWidth,
          titleTextStyle: other.titleTextStyle ?? titleTextStyle,
          descriptionTextStyle: other.descriptionTextStyle ?? descriptionTextStyle,
          textGap: other.textGap ?? textGap,
          iconTheme: other.iconTheme ?? iconTheme,
          chevronColour: other.chevronColour ?? chevronColour,
          chevronSize: other.chevronSize ?? chevronSize,
          dividerColour: other.dividerColour ?? dividerColour,
          dividerThickness: other.dividerThickness ?? dividerThickness,
          disabledOpacity: other.disabledOpacity ?? disabledOpacity,
          groupLabelTextStyle: other.groupLabelTextStyle ?? groupLabelTextStyle,
          groupLabelGap: other.groupLabelGap ?? groupLabelGap,
          groupGap: other.groupGap ?? groupGap,
          listPadding: other.listPadding ?? listPadding,
          listGap: other.listGap ?? listGap,
          emptyTextStyle: other.emptyTextStyle ?? emptyTextStyle,
          selectedIconColour: other.selectedIconColour ?? selectedIconColour,
        );

  /// Interpolate towards `other` — what `ThemeData.lerp` calls when a theme
  /// animates between two schemes. A field with no half-way value snaps at
  /// t = 0.5 rather than inventing one.
  LumoItemStyle lerp(LumoItemStyle other, double t) => LumoItemStyle(
        gap: _lerpMap<LumoItemSize, double>(gap, other.gap, t, lerpDouble),
        inlinePadding: _lerpMap<LumoItemSize, double>(inlinePadding, other.inlinePadding, t, lerpDouble),
        blockPadding: _lerpMap<LumoItemSize, double>(blockPadding, other.blockPadding, t, lerpDouble),
        minHeight: lerpDouble(minHeight, other.minHeight, t),
        borderRadius: BorderRadiusGeometry.lerp(borderRadius, other.borderRadius, t),
        background: _lerpMap<LumoItemVariant, Color>(background, other.background, t, Color.lerp),
        selectedBackground: Color.lerp(selectedBackground, other.selectedBackground, t),
        pressedBackground: Color.lerp(pressedBackground, other.pressedBackground, t),
        borderColour: Color.lerp(borderColour, other.borderColour, t),
        borderWidth: lerpDouble(borderWidth, other.borderWidth, t),
        titleTextStyle: TextStyle.lerp(titleTextStyle, other.titleTextStyle, t),
        descriptionTextStyle: TextStyle.lerp(descriptionTextStyle, other.descriptionTextStyle, t),
        textGap: lerpDouble(textGap, other.textGap, t),
        iconTheme: _lerpIconTheme(iconTheme, other.iconTheme, t),
        chevronColour: Color.lerp(chevronColour, other.chevronColour, t),
        chevronSize: lerpDouble(chevronSize, other.chevronSize, t),
        dividerColour: Color.lerp(dividerColour, other.dividerColour, t),
        dividerThickness: lerpDouble(dividerThickness, other.dividerThickness, t),
        disabledOpacity: lerpDouble(disabledOpacity, other.disabledOpacity, t),
        groupLabelTextStyle: TextStyle.lerp(groupLabelTextStyle, other.groupLabelTextStyle, t),
        groupLabelGap: lerpDouble(groupLabelGap, other.groupLabelGap, t),
        groupGap: lerpDouble(groupGap, other.groupGap, t),
        listPadding: EdgeInsetsGeometry.lerp(listPadding, other.listPadding, t),
        listGap: lerpDouble(listGap, other.listGap, t),
        emptyTextStyle: TextStyle.lerp(emptyTextStyle, other.emptyTextStyle, t),
        selectedIconColour: Color.lerp(selectedIconColour, other.selectedIconColour, t),
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LumoItemStyle &&
          mapEquals(gap, other.gap) &&
          mapEquals(inlinePadding, other.inlinePadding) &&
          mapEquals(blockPadding, other.blockPadding) &&
          minHeight == other.minHeight &&
          borderRadius == other.borderRadius &&
          mapEquals(background, other.background) &&
          selectedBackground == other.selectedBackground &&
          pressedBackground == other.pressedBackground &&
          borderColour == other.borderColour &&
          borderWidth == other.borderWidth &&
          titleTextStyle == other.titleTextStyle &&
          descriptionTextStyle == other.descriptionTextStyle &&
          textGap == other.textGap &&
          iconTheme == other.iconTheme &&
          chevronColour == other.chevronColour &&
          chevronSize == other.chevronSize &&
          dividerColour == other.dividerColour &&
          dividerThickness == other.dividerThickness &&
          disabledOpacity == other.disabledOpacity &&
          groupLabelTextStyle == other.groupLabelTextStyle &&
          groupLabelGap == other.groupLabelGap &&
          groupGap == other.groupGap &&
          listPadding == other.listPadding &&
          listGap == other.listGap &&
          emptyTextStyle == other.emptyTextStyle &&
          selectedIconColour == other.selectedIconColour;

  @override
  int get hashCode => Object.hashAll([
        _hashMap(gap),
        _hashMap(inlinePadding),
        _hashMap(blockPadding),
        minHeight,
        borderRadius,
        _hashMap(background),
        selectedBackground,
        pressedBackground,
        borderColour,
        borderWidth,
        titleTextStyle,
        descriptionTextStyle,
        textGap,
        iconTheme,
        chevronColour,
        chevronSize,
        dividerColour,
        dividerThickness,
        disabledOpacity,
        groupLabelTextStyle,
        groupLabelGap,
        groupGap,
        listPadding,
        listGap,
        emptyTextStyle,
        selectedIconColour,
      ]);
}

mixin _$LumoStyles on ThemeExtension<LumoStyles> {
  LumoButtonStyle get button;
  LumoCardStyle get card;
  LumoItemStyle get item;

  @override
  LumoStyles copyWith({LumoButtonStyle? button, LumoCardStyle? card, LumoItemStyle? item}) => LumoStyles(button: button ?? this.button, card: card ?? this.card, item: item ?? this.item);

  @override
  LumoStyles lerp(covariant LumoStyles? other, double t) => other == null ? copyWith() : LumoStyles(button: button.lerp(other.button, t), card: card.lerp(other.card, t), item: item.lerp(other.item, t));

  @override
  bool operator ==(Object other) => identical(this, other) || other is LumoStyles && other.button == button && other.card == card && other.item == item;

  @override
  int get hashCode => Object.hashAll([button, card, item]);
}

/// Two per-step tables interpolated key by key. A key only ONE side carries has
/// nothing to interpolate against, so it SNAPS at the half-way point: fading a
/// value towards a default the other side never named draws a colour that is in
/// neither theme.
Map<K, V>? _lerpMap<K, V>(Map<K, V>? a, Map<K, V>? b, double t, V? Function(V?, V?, double) lerp) {
  if (a == null && b == null) return null;
  final out = <K, V>{};
  for (final key in <K>{...?a?.keys, ...?b?.keys}) {
    final x = a?[key];
    final y = b?[key];
    final v = x == null || y == null ? (t < 0.5 ? x : y) : lerp(x, y, t);
    if (v != null) out[key] = v;
  }
  return out;
}

/// Order-independent, because a table's order is not part of its meaning.
int? _hashMap<K, V>(Map<K, V>? map) => map == null ? null : Object.hashAllUnordered(map.entries.map((e) => Object.hash(e.key, e.value)));

/// `IconThemeData.lerp` answers two nulls with an all-null OBJECT rather than
/// null, which would turn «nothing set» into «everything set to nothing» the
/// first time a theme animated.
IconThemeData? _lerpIconTheme(IconThemeData? a, IconThemeData? b, double t) => a == null && b == null ? null : IconThemeData.lerp(a, b, t);
