/* GENERATED by scripts/build-native-tokens.mjs from packages/theme/src/tokens.css — do not edit.
 * The same `--lumo-sys-*` semantic tokens as the web theme, resolved for React
 * Native: hex colours (oklch → sRGB) for the light and dark schemes, dp for
 * radii and control heights (rem × 16 at the default density 0.9 and radius
 * scale 1). Brand hue/chroma are the one runtime knob, as on the web. */

/** The web theme's ref-tier knobs: `--lumo-ref-{hue,chroma}-brand` and `-neutral`. Default achromatic, as on the web. */
export interface LumoBrand {
  hue: number;
  chroma: number;
  neutralHue: number;
  neutralChroma: number;
}
export const ACHROMATIC: LumoBrand = { hue: 0, chroma: 0, neutralHue: 0, neutralChroma: 0 };

/** oklch(L C h) → #rrggbb (sRGB, gamut-clipped) — the ramp's lightness is fixed; a brand turns only hue and chroma. */
export function oklch(L: number, C: number, h: number): string {
  const a = C * Math.cos((h * Math.PI) / 180);
  const b = C * Math.sin((h * Math.PI) / 180);
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ ** 3, m = m_ ** 3, s = s_ ** 3;
  const lin = [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
  return (
    "#" +
    lin
      .map((c) => {
        const v = Math.min(1, Math.max(0, c));
        const srgb = v <= 0.0031308 ? 12.92 * v : 1.055 * v ** (1 / 2.4) - 0.055;
        return Math.round(srgb * 255).toString(16).padStart(2, "0");
      })
      .join("")
  );
}

export interface LumoSchemeColours {
  bg: string;
  bgSubtle: string;
  surface: string;
  surfaceHover: string;
  surfaceSunken: string;
  fg: string;
  fgMuted: string;
  fgSubtle: string;
  fgOnAccent: string;
  border: string;
  borderStrong: string;
  borderControl: string;
  accent: string;
  accentHover: string;
  accentFg: string;
  positive: string;
  critical: string;
  caution: string;
  focus: string;
  scrim: string;
}

export function lightColours(brand: LumoBrand = ACHROMATIC): LumoSchemeColours {
  return {
    bg: oklch(0.985, brand.neutralChroma, brand.neutralHue),
    bgSubtle: oklch(0.97, brand.neutralChroma, brand.neutralHue),
    surface: "#ffffff",
    surfaceHover: oklch(0.97, brand.neutralChroma, brand.neutralHue),
    surfaceSunken: oklch(0.97, brand.neutralChroma, brand.neutralHue),
    fg: oklch(0.145, brand.neutralChroma, brand.neutralHue),
    fgMuted: oklch(0.5, brand.neutralChroma, brand.neutralHue),
    fgSubtle: oklch(0.54, brand.neutralChroma, brand.neutralHue),
    fgOnAccent: oklch(0.985, brand.neutralChroma, brand.neutralHue),
    border: oklch(0.922, brand.neutralChroma, brand.neutralHue),
    borderStrong: oklch(0.845, brand.neutralChroma, brand.neutralHue),
    borderControl: oklch(0.64, brand.neutralChroma, brand.neutralHue),
    accent: oklch(0.205, brand.chroma, brand.hue),
    accentHover: oklch(0.32, brand.chroma, brand.hue),
    accentFg: oklch(0.985, brand.neutralChroma, brand.neutralHue),
    positive: "#00763f",
    critical: "#bf0000",
    caution: "#8f5b00",
    focus: oklch(0.32, brand.chroma, brand.hue),
    scrim: "#00000080",
  };
}

export function darkColours(brand: LumoBrand = ACHROMATIC): LumoSchemeColours {
  return {
    bg: oklch(0.145, brand.neutralChroma, brand.neutralHue),
    bgSubtle: oklch(0.205, brand.neutralChroma, brand.neutralHue),
    surface: oklch(0.205, brand.neutralChroma, brand.neutralHue),
    surfaceHover: oklch(0.269, brand.neutralChroma, brand.neutralHue),
    surfaceSunken: oklch(0.145, brand.neutralChroma, brand.neutralHue),
    fg: oklch(0.985, brand.neutralChroma, brand.neutralHue),
    fgMuted: oklch(0.71, brand.neutralChroma, brand.neutralHue),
    fgSubtle: oklch(0.66, brand.neutralChroma, brand.neutralHue),
    fgOnAccent: oklch(0.205, brand.neutralChroma, brand.neutralHue),
    border: oklch(0.383, brand.neutralChroma, brand.neutralHue),
    borderStrong: oklch(0.47, brand.neutralChroma, brand.neutralHue),
    borderControl: oklch(0.556, brand.neutralChroma, brand.neutralHue),
    accent: oklch(0.922, brand.chroma, brand.hue),
    accentHover: oklch(0.75, brand.chroma, brand.hue),
    accentFg: oklch(0.205, brand.neutralChroma, brand.neutralHue),
    positive: "#3bb974",
    critical: "#ff6467",
    caution: "#eba941",
    focus: oklch(0.922, brand.chroma, brand.hue),
    scrim: "#000000b8",
  };
}

/** Radii in dp (web: --lumo-sys-radius-*). */
export const radius = { sm: 6, md: 8, lg: 10 } as const;
/** Control heights in dp at the default density (web: --lumo-ref-control-*). */
export const control = { sm: 29, md: 36, lg: 44 } as const;
/** Focus ring (web: --lumo-sys-focus-width / -offset). */
export const focus = { width: 2, offset: 2 } as const;
