#!/usr/bin/env node
/**
 * THE MOBILE CONSUMER SMOKE TEST — the Dart counterpart of `gate:smoke`.
 *
 * Everything else verifies the mobile library against itself, from inside the
 * workspace. This builds a throwaway Flutter package OUTSIDE it, depends on
 * `lumo_ui_mobile` by path, imports nothing but the barrel, names every public
 * widget and enum the API reference documents, and analyses it.
 *
 * A component can be perfect inside the workspace and uninstallable outside it.
 * Concretely, this fails when:
 *
 *   - `packages/mobile/pubspec.yaml` is missing a dependency the library uses.
 *     Inside the monorepo another package's pub cache can make that invisible;
 *     a consumer with only the declared dependencies gets a compile error.
 *   - the barrel does not export something the docs site documents, so a reader
 *     is shown API they cannot import. (Found 17 Aug 2026: `date_value_box.dart`
 *     had two documented widgets and no `export` line. The API generator now
 *     reads the barrel, and this gate is the other half of that fix.)
 *   - a public signature names a type that is itself not exported, which
 *     compiles in-package and not out of it.
 *
 * Not in `verify` by default — it runs `flutter pub get` against a scratch
 * directory. CI runs it beside the other mobile gates.
 */

import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import { SEARCHED, findFlutter, flutterRunner } from "./lib/flutter.mjs";

const ROOT = resolve(import.meta.dirname, "..");
const PACKAGE = join(ROOT, "packages", "mobile");

/** @type {{ widgets: Record<string, { file: string }>, enums: Record<string, string[]> }} */
const api = JSON.parse(readFileSync(join(ROOT, "mobile-api-reference.json"), "utf8"));
const widgets = Object.keys(api.widgets).sort();
const enums = Object.keys(api.enums).sort();

const sdk = findFlutter();
if (!sdk) {
  console.error(`  smoke-mobile: no Flutter SDK found (${SEARCHED}).`);
  process.exit(1);
}

const scratch = mkdtempSync(join(tmpdir(), "lumo-mobile-consumer-"));
try {
  mkdirSync(join(scratch, "lib"), { recursive: true });
  writeFileSync(
    join(scratch, "pubspec.yaml"),
    [
      "name: lumo_consumer_smoke",
      "description: A throwaway consumer of lumo_ui_mobile, outside the workspace.",
      "publish_to: none",
      "version: 0.0.0",
      "",
      "environment:",
      "  sdk: ^3.9.0",
      "",
      "dependencies:",
      "  flutter:",
      "    sdk: flutter",
      "  lumo_ui_mobile:",
      `    path: ${PACKAGE}`,
      "",
      "dev_dependencies:",
      "  flutter_lints: ^5.0.0",
      "",
      "flutter:",
      "  uses-material-design: true",
      "",
    ].join("\n"),
  );

  // ONLY the barrel. A consumer that has to reach into `src/` is a consumer
  // whose imports we broke.
  const lines = [
    "// GENERATED by scripts/smoke-mobile.mjs — a scratch consumer, never committed.",
    "// Naming a type is enough: it resolves only if the barrel exports it and",
    "// every type in its signature is reachable from outside the package.",
    "import 'package:flutter/widgets.dart';",
    "import 'package:lumo_ui_mobile/lumo_ui_mobile.dart';",
    "",
    "const List<Type> publicWidgets = <Type>[",
    ...widgets.map((name) => `  ${name},`),
    "];",
    "",
    "const List<Type> publicEnums = <Type>[",
    ...enums.map((name) => `  ${name},`),
    "];",
    "",
    "// The scope is the one widget every consumer must build, so build it.",
    "Widget smoke(Widget child) => LumoScope(",
    "      locale: 'fa-IR',",
    "      brightness: Brightness.light,",
    "      child: child,",
    "    );",
    "",
  ];
  writeFileSync(join(scratch, "lib", "consumer.dart"), lines.join("\n"));

  const run = flutterRunner(sdk, scratch);
  if (run(["pub", "get"]) !== 0) {
    console.error("  smoke-mobile: `flutter pub get` failed in a bare consumer — the package's own");
    console.error("  pubspec does not declare everything it needs.");
    process.exit(1);
  }
  if (run(["analyze", "--no-pub"]) !== 0) {
    console.error("  smoke-mobile: a bare consumer does not compile against the barrel.");
    console.error("  Every name above comes from mobile-api-reference.json, so anything unresolved is");
    console.error("  documented API that cannot be imported.");
    process.exit(1);
  }
  console.log(
    `  smoke-mobile: ${String(widgets.length)} widget(s) and ${String(enums.length)} enum(s) resolve from the barrel ` +
      "in a consumer outside the workspace",
  );
} finally {
  rmSync(scratch, { recursive: true, force: true });
}
